[package]
edition = "2018"
name = "learning-backpropagation"
version = "0.1.0"

[dependencies]
nalgebra = "0.28.0"
rand = "0.8.4"
serde = {version = "1.0.129", features = ["derive"]}
serde_json = "1.0.66"
