[package]
edition = "2018"
name = "learning-backpropagation"
version = "0.1.0"

[dependencies]
nalgebra = "0.28.0"
rand = "0.8.4"
rayon = "1.5.1"
serde_json = "1.0.66"

[dependencies.serde]
features = ["derive"]
version = "1.0.129"
