pub mod backpropagation;
pub mod configuration;
pub mod functions;
pub mod generation;
pub mod gradient_descent;
pub mod linear_algebra;
pub mod neural_network;
pub mod training;
pub mod training_data;
